version: 2
jobs:
  build:
    working_directory: ~/ci-demo
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: cd ~/ci-demo && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=lcov'
      - run:
          name: zip-result
          command: 'tar cvzf coverage.tgz ~/ci-demo/coverage';
      - store_artifacts:
        	path: ~/ci-demo/coverage.tgz